# Generated by Django 6.0.3 on 2026-05-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_empleado_direccion_empleado_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo sugerido'),
        ),
    ]
