# Generated by Django 6.0.3 on 2026-05-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_plato_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='costo',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de compra'),
        ),
    ]
