# Generated by Django 6.0.3 on 2026-05-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_produccion_recetaproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['rol', 'turno', 'apellido', 'nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
