# Generated by Django 6.0.3 on 2026-05-20 00:18

import datetime

from django.db import migrations, models


TURNOS = [
    ('Mañana', datetime.time(6, 0), datetime.time(14, 0)),
    ('Tarde', datetime.time(14, 0), datetime.time(22, 0)),
    ('Noche', datetime.time(22, 0), datetime.time(6, 0)),
]


def crear_turnos(apps, schema_editor):
    Turno = apps.get_model('api', 'Turno')
    for nombre, inicio, fin in TURNOS:
        Turno.objects.create(nombre=nombre, hora_inicio=inicio, hora_fin=fin)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_empleado_options_empleado_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.RunPython(crear_turnos),
        migrations.AlterField(
            model_name='empleado',
            name='turno',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
