# Generated by Django 6.0.3 on 2026-05-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_turno_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
