# Generated by Django 6.0.3 on 2026-05-21 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_empleado_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('capacidad', models.IntegerField(default=4)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('empleado', models.ForeignKey(limit_choices_to={'activo': True, 'rol__nombre': 'Mesero'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_mesa', to='api.empleado')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_mesa', to='api.turno')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='api.mesa')),
            ],
            options={
                'verbose_name': 'Asignación de mesa',
                'verbose_name_plural': 'Asignaciones de mesas',
                'ordering': ['fecha', 'turno__hora_inicio', 'mesa__numero'],
                'unique_together': {('mesa', 'turno', 'fecha')},
            },
        ),
    ]
