# Generated by Django 6.0.3 on 2026-05-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='turno',
        ),
    ]
