# Generated by Django 6.0.3 on 2026-05-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_reserva_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='imagen',
            field=models.URLField(blank=True, verbose_name='URL de imagen'),
        ),
    ]
